# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-29 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_card', models.CharField(max_length=100)),
                ('from_eth_account', models.CharField(max_length=100)),
                ('to_card', models.CharField(max_length=100)),
                ('to_eth_account', models.CharField(max_length=100)),
            ],
        ),
    ]
