# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-30 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='charged_amount',
            field=models.BigIntegerField(default=0),
        ),
    ]
