# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSessionData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100)),
                ('session_passwd', models.CharField(max_length=4)),
                ('isEnable', models.BooleanField(default=True)),
                ('isRevoked', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='GameSession',
        ),
    ]
