# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170427_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesessiondata',
            name='members',
            field=models.CharField(max_length=900, null=True),
        ),
    ]
