# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 04:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_gamesessiondata_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamesessiondata',
            name='isEnable',
        ),
    ]
