# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-28 02:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_gamesessiondata_isenable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesessiondata',
            name='members',
            field=models.CharField(default='', max_length=900),
        ),
    ]
